### ISSUE TITLE
为什么不会出现死循环

### ISSUE THREAD

**Issue by 18518251995** [OpenFibers/OTScreenshotHelper#1]
UIView+ComOpenThreadOTScreenshotHelperStatusBarReference中

+ (UIView *)statusBarInstance_ComOpenThreadOTScreenshotHelper
{
    return statusBarInstance;
}

+ (void)load
{
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        Class statusBarClass = NSClassFromString(@"UIStatusBar");
        [ComOpenThreadOTScreenshotHelperSwizzleHelper swizzClass:statusBarClass
                           selector:@selector(setFrame:)
                           selector:@selector(setFrameIntercept_ComOpenThreadOTScreenshotHelper:)];
        [ComOpenThreadOTScreenshotHelperSwizzleHelper swizzClass:statusBarClass
                           selector:NSSelectorFromString(@"dealloc")
                           selector:@selector(deallocIntercept_ComOpenThreadOTScreenshotHelper)];
    });
}

- (void)setFrameIntercept_ComOpenThreadOTScreenshotHelper:(CGRect)frame
{
    [self setFrameIntercept_ComOpenThreadOTScreenshotHelper:frame];
    statusBarInstance = self;
}

- (void)deallocIntercept_ComOpenThreadOTScreenshotHelper
{
    statusBarInstance = nil;
    [self deallocIntercept_ComOpenThreadOTScreenshotHelper];
}
这里面 [self setFrameIntercept_ComOpenThreadOTScreenshotHelper:frame];循环调用为什么没有死循环

**Comment by LemonChao** [comment]
这是典型的在运行时hook系统的方法调用
在load方法里 把 setFrame: 跟 setFrameIntercept_ComOpenThreadOTScreenshotHelper:做了交换
这样在调用setFrame: 之前会先调用自己的setFrameIntercept_ComOpenThreadOTScreenshotHelper:
`(void)setFrameIntercept_ComOpenThreadOTScreenshotHelper:(CGRect)frame
{
//实际是调用系统类 setFrame: 因为前面已经做过交换了
[self setFrameIntercept_ComOpenThreadOTScreenshotHelper:frame];
statusBarInstance = self;
}`

**Comment by OpenFibers** [comment]
@18518251995 这个是最基础的 method swizzling
@LemonChao 在StatusBar初始化前hook其setFrame方法，一旦StatusBar的实例调用setFrame，记录实例到内存。然后用此实例renderInContext，即可对status bar截图

**Comment by LemonChao** [comment]
@OpenFibers 仔细读了源码算是明白了，感谢分享！！
一个小建议：
获取statusBar实例也可以用这个方法获取
`UIView *statusBarView = [[[UIApplication sharedApplication] valueForKey:@"statusBarWindow"] valueForKey:@"statusBar"];`
代码更简洁一些

**Comment by OpenFibers** [comment]
也可以，当时怕审核踩雷，没敢用kvc，可以试试看
