### ISSUE TITLE
状态栏没有时间

### ISSUE THREAD

**Issue by LewinJun** [OpenFibers/OTScreenshotHelper#2]
是否可以加上时间

**Comment by Realank** [comment]
问题解决了，小哥记得下次用英文提问

**Comment by OpenFibers** [comment]
Thanks for @Realank 's amazing pull request

**Comment by OpenFibers** [comment]
@Realank 老铁要不要了解一下阿里的职位 flutter/iOS 都有

**Comment by Realank** [comment]
@OpenFibers 老铁666啊，难道是咸鱼团队？暂时不打算换工作，需要的时候还请拜托引荐啊～

**Comment by LewinJun** [comment]
> 问题解决了，小哥记得下次用英文提问

多谢，我早就自己解决了。

**Comment by OpenFibers** [comment]
@Realank 收到~

集团做flutter的兄弟是大多数在闲鱼
